"""admin and member-attendance

Revision ID: 209d9bd046e6
Revises: 
Create Date: 2024-01-20 16:43:46.604565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "209d9bd046e6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin",
        sa.Column("admin_uid", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("installation", sa.String(), nullable=False),
        sa.Column("admin_type", sa.String(), nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("admin_uid"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("phone_number"),
    )
    op.create_table(
        "attendance",
        sa.Column("uid", sa.UUID(), nullable=False),
        sa.Column("member_uid", sa.UUID(), nullable=True),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("sunday_service", sa.Boolean(), nullable=False),
        sa.Column("midweek_service", sa.Boolean(), nullable=False),
        sa.Column("is_guest", sa.Boolean(), nullable=False),
        sa.Column("guest_installation", sa.String(), nullable=True),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("uid"),
    )
    op.create_index(
        op.f("ix_attendance_member_uid"), "attendance", ["member_uid"], unique=False
    )
    op.create_table(
        "members",
        sa.Column("member_uid", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("installation", sa.String(), nullable=False),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("tribe", sa.String(), nullable=False),
        sa.Column("date_created_utc", sa.DateTime(), nullable=True),
        sa.Column("date_updated_utc", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("member_uid"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("members")
    op.drop_index(op.f("ix_attendance_member_uid"), table_name="attendance")
    op.drop_table("attendance")
    op.drop_table("admin")
    # ### end Alembic commands ###
