"""added the other columns

Revision ID: 5111accfab2d
Revises: 209d9bd046e6
Create Date: 2024-01-21 20:03:44.876866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5111accfab2d"
down_revision: Union[str, None] = "209d9bd046e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "attendance", sa.Column("global_gethsemane", sa.Boolean(), nullable=False)
    )
    op.add_column("members", sa.Column("checkin_token", sa.String(), nullable=True))
    op.add_column("members", sa.Column("is_first_time", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("members", "is_first_time")
    op.drop_column("members", "checkin_token")
    op.drop_column("attendance", "global_gethsemane")
    # ### end Alembic commands ###
